import { Link, useParams } from 'react-router-dom'
import { useState } from 'react'
import { ThumbsDown, ThumbsUp } from 'lucide-react'
import './HelpTopic.css'

const TOPICS: Record<string, { title: string; paragraphs: string[] }> = {
  atendimento: { title: 'Atendimento ao cliente', paragraphs: ['A equipe TEKNIX está disponível para ajudar com dúvidas sobre produtos, compras, pagamentos, entregas, trocas e devoluções.', 'Antes de falar conosco, tenha em mãos o número do pedido e o e-mail ou telefone utilizado na compra.', 'Você pode consultar seus pedidos, acompanhar a entrega e encontrar orientações na Central de Ajuda. Se ainda precisar de suporte, acesse a página de contato pelos canais oficiais.'] },
  'termo-compra-venda': { title: 'Termo de compra e venda', paragraphs: ['Este termo apresenta as condições gerais aplicáveis às compras realizadas nos canais oficiais da TEKNIX.', 'Ao concluir um pedido, o cliente confirma os dados do produto, quantidade, preço, forma de pagamento, endereço e condições de entrega apresentadas no checkout.', 'A aprovação do pagamento, a disponibilidade do estoque, a emissão fiscal, a entrega, as trocas, as devoluções e a garantia seguem as condições informadas no pedido e a legislação brasileira aplicável.', 'Em caso de dúvida sobre uma compra específica, consulte os detalhes do pedido ou fale com o atendimento TEKNIX.'] },
  'assistencia-tecnica': { title: 'Assistência técnica de fábrica', paragraphs: ['A assistência técnica depende do produto, do fabricante e do prazo de garantia informado no anúncio ou na nota fiscal.', 'Antes de solicitar atendimento, reúna o número do pedido, a nota fiscal, fotos ou vídeos do problema e uma descrição detalhada do que aconteceu.', 'Não tente abrir ou modificar o produto quando isso puder afetar a garantia. Nossa equipe orientará os próximos passos, incluindo envio para análise, reparo ou outra solução aplicável.', 'O prazo de avaliação pode variar conforme o fabricante, o tipo de produto e a disponibilidade de peças.'] },
  'politica-privacidade': { title: 'Política de privacidade', paragraphs: ['A TEKNIX utiliza dados pessoais para criar contas, processar pedidos, realizar entregas, prestar atendimento, emitir documentos fiscais e proteger a plataforma.', 'Compartilhamos somente as informações necessárias com meios de pagamento, transportadoras, fornecedores de tecnologia e autoridades quando houver obrigação legal.', 'Você pode solicitar informações, correção de dados e outros direitos previstos na legislação aplicável através dos canais oficiais de atendimento.', 'Para ver a política completa de Segurança e Privacidade, acesse também a página legal da TEKNIX.'] },
  regulamentos: { title: 'Regulamentos', paragraphs: ['Esta área reúne as condições gerais de promoções, cupons, descontos, benefícios, frete e demais campanhas da TEKNIX.', 'Cada campanha pode ter prazo, estoque, produtos participantes, valor mínimo, região e forma de pagamento específicos.', 'Antes de concluir a compra, confira sempre o preço, o desconto aplicado, o frete e as condições apresentadas no checkout.', 'As promoções continuam sujeitas às regras de cancelamento, troca, devolução, garantia e direito de arrependimento previstas na legislação brasileira.'] },
  'direito-arrependimento': { title: 'Direito de arrependimento de compra', paragraphs: ['Você tem o prazo legal de até 7 dias corridos, contados do recebimento do produto, para se arrepender da compra.', 'Para solicitar, acesse Minha conta > Compras e escolha a compra correspondente. Depois, siga as instruções para iniciar a devolução e falar com o vendedor quando necessário.', 'O produto deve ser devolvido, sempre que possível, na embalagem original, com todos os acessórios, manuais e itens que o acompanham. Isso ajuda a garantir que a análise da devolução seja concluída sem atrasos.', 'Depois de solicitar a devolução, você receberá as orientações para preparar o pacote e realizar o envio. Guarde o comprovante até que o processo seja finalizado.', 'Após o recebimento e a conferência do produto, o reembolso será encaminhado conforme a forma de pagamento utilizada na compra. O prazo pode variar de acordo com o banco ou a administradora do cartão.', 'Para acompanhar o processo, volte à área de Compras e consulte o status da solicitação. Se tiver qualquer problema, entre em contato com a equipe TEKNIX informando o número do pedido.'] },
  'como-escolher-vendedor': { title: 'Como escolher de qual vendedor comprar', paragraphs: ['Se você gostou de um produto e está com dúvidas em relação ao vendedor, veja algumas dicas para escolher com mais segurança.', 'Verifique a cor da reputação e a experiência do vendedor. Os vendedores que mantêm um bom histórico costumam oferecer atendimento mais consistente e cumprir melhor os prazos informados.', 'Se o vendedor tiver uma medalha de destaque, isso significa que ele alcançou bons resultados em vendas e atendimento, além de cumprir os critérios de qualidade da plataforma.', 'Leia em detalhe o anúncio antes de comprar. Confira a descrição, as fotos, as medidas, os materiais e tudo o que acompanha o produto.', 'Revise atentamente as condições de venda e entrega. Veja o prazo de envio, o valor do frete, a previsão de chegada e as regras de devolução.', 'Se o produto for novo, confirme se possui garantia e se a nota fiscal será enviada. Em caso de produto usado, leia com cuidado o estado de conservação informado.', 'Tire todas as dúvidas antes de finalizar. Use o campo de perguntas do anúncio para falar com o vendedor e confirme qualquer informação que não esteja clara.', 'Compare diferentes anúncios do mesmo produto. Você pode usar filtros, ordenar por preço e observar as avaliações de compradores que já receberam o item.', 'Além do preço, considere o prazo de entrega, a reputação do vendedor, a garantia e as condições de devolução. A opção mais barata nem sempre é a melhor escolha.', 'Depois de comparar tudo, escolha o anúncio que oferece o melhor conjunto de preço, segurança, prazo e atendimento para a sua compra.'] },
  'como-pagar': { title: 'Como pagar a sua compra', paragraphs: ['Escolha uma forma de pagamento disponível no checkout, como cartão, PIX ou outras opções oferecidas para o produto.', 'Antes de confirmar, confira o valor total, o parcelamento e o prazo de aprovação do pagamento.'] },
  'protecao-compradores': { title: 'Como protegemos os compradores', paragraphs: ['A TEKNIX acompanha sua compra para ajudar quando o produto não chega, chega diferente do anúncio ou apresenta um problema.', 'Guarde as mensagens, comprovantes e fotos do produto para facilitar qualquer solicitação de suporte.'] },
  'garantia-produto': { title: 'Como estender a garantia de um produto', paragraphs: ['A disponibilidade da garantia depende do produto e das condições informadas na oferta.', 'Consulte os detalhes da compra ou fale com nosso atendimento para verificar as opções disponíveis.'] },
  'frete-gratis': { title: 'Como funciona o benefício de frete grátis', paragraphs: ['O benefício de frete grátis depende do produto, da região de entrega e das condições da campanha vigente.', 'Confira o valor e o prazo de entrega antes de concluir a compra.'] },
  'cupons': { title: 'Como usar cupons na minha compra', paragraphs: ['Na etapa de pagamento, informe o código do cupom no campo indicado e aplique o desconto.', 'Cada cupom pode ter regras de validade, valor mínimo e produtos participantes.'] },
  'devolucoes': { title: 'Devoluções e reembolsos', paragraphs: ['Para devolver um produto, acesse seus pedidos e selecione a compra que deseja devolver.', 'Siga as orientações de embalagem e envio. O reembolso será processado conforme a forma de pagamento e as condições da devolução.'] },
  'entregas': { title: 'Entregas e envios', paragraphs: ['Você pode acompanhar o status e a previsão de entrega na área de pedidos.', 'Caso a entrega atrase ou o rastreamento não seja atualizado, entre em contato com nosso atendimento.'] },
  'perguntas-anuncio': { title: 'Perguntar em um anúncio', paragraphs: ['Use o campo de perguntas na página do produto para tirar dúvidas diretamente sobre o item antes de finalizar a compra.', 'Você pode perguntar sobre medidas, material, cor, compatibilidade, voltagem, garantia, prazo de envio e os acessórios que acompanham o produto.', 'Leia primeiro a descrição e as especificações do anúncio. Assim, você evita repetir uma dúvida que já foi respondida e consegue fazer uma pergunta mais objetiva.', 'Escreva uma pergunta clara e informe somente o que precisa saber para decidir. O vendedor poderá responder diretamente no anúncio.', 'Não compartilhe dados pessoais, senhas, códigos de segurança ou informações de pagamento nas mensagens.', 'Depois que sua pergunta for respondida, revise a informação junto com a descrição, as fotos e as avaliações de outros compradores.', 'Se a resposta não resolver sua dúvida, compare outro anúncio ou fale com a equipe TEKNIX antes de concluir a compra.'] },
}

const FALLBACK = { title: 'Ajuda sobre sua compra', paragraphs: ['Encontre orientações para resolver dúvidas sobre sua compra, pagamento, entrega ou devolução.', 'Se ainda precisar de ajuda, fale com a equipe TEKNIX.'] }
const PURCHASE_LINKS = [
  ['Direito de arrependimento de compra', 'direito-arrependimento'], ['Como escolher de qual vendedor comprar', 'como-escolher-vendedor'], ['Como pagar a sua compra', 'como-pagar'], ['Como protegemos os compradores', 'protecao-compradores'], ['Como estender a garantia de um produto', 'garantia-produto'], ['Como o meu benefício de frete grátis funciona', 'frete-gratis'], ['Como usar cupons na minha compra', 'cupons'], ['Devoluções e reembolsos', 'devolucoes'], ['Entregas e envios', 'entregas'], ['Perguntar em um anúncio', 'perguntas-anuncio'],
]

export default function HelpTopic() {
  const { slug = '' } = useParams()
  const [feedback, setFeedback] = useState<'yes' | 'no' | null>(null)
  if (slug === 'compras') return <main className="help-topic-page"><div className="help-topic-inner"><nav className="help-breadcrumb"><Link to="/ajuda">Ajuda</Link><span>›</span><span>Compras</span></nav><h1>Compras</h1><div className="help-topic-list-card">{PURCHASE_LINKS.map(([label, itemSlug]) => <Link to={`/ajuda/${itemSlug}`} key={itemSlug}><span>{label}</span><span>›</span></Link>)}</div></div></main>
  const topic = TOPICS[slug] || FALLBACK
  return <main className="help-topic-page"><div className="help-topic-inner"><nav className="help-breadcrumb"><Link to="/ajuda">Ajuda</Link><span>›</span><Link to="/ajuda/compras">Compras</Link><span>›</span><span>{topic.title}</span></nav><h1>{topic.title}</h1><article className="help-topic-card">{topic.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}<div className="help-feedback"><strong>{feedback ? (feedback === 'yes' ? 'Obrigado pelo feedback!' : 'Obrigado. Vamos melhorar esse conteúdo.') : 'Isso foi útil?'}</strong>{!feedback && <><button type="button" aria-label="Sim, foi útil" onClick={() => setFeedback('yes')}><ThumbsUp size={18} /></button><button type="button" aria-label="Não foi útil" onClick={() => setFeedback('no')}><ThumbsDown size={18} /></button></>}</div></article></div></main>
}
