import { Link, useParams } from 'react-router-dom'
import './LegalPage.css'

const CONTENT: Record<string, { title: string; paragraphs: string[] }> = {
  regulamento: { title: 'Regulamento TEKNIX', paragraphs: ['Última atualização: 08 de setembro de 2026.', 'Bem-vindo à área de Regulamentos da TEKNIX. Esta página reúne as principais condições aplicáveis às promoções, campanhas, cupons, descontos, benefícios e demais ações comerciais realizadas em nossos canais oficiais.', 'As promoções poderão possuir período de validade, produtos participantes, quantidade disponível, valor mínimo, região atendida, forma de pagamento e outras condições apresentadas durante a campanha.', 'Os preços podem ser alterados a qualquer momento. O preço e a disponibilidade serão confirmados no momento da conclusão do pedido; produtos adicionados à sacola não possuem preço reservado.', 'Cupons podem ter prazo de validade, valor mínimo, produtos participantes, limite por cliente, região e forma de pagamento elegível. Salvo indicação expressa, cupons não são cumulativos.', 'Todas as ofertas estão sujeitas à disponibilidade de estoque. Campanhas de frete grátis ou promocional podem depender de CEP, produto, categoria, valor mínimo, modalidade de entrega ou período da campanha.', 'A TEKNIX poderá estabelecer limites de unidades por pedido, CPF, conta, endereço ou cliente e poderá impedir o uso de benefícios quando identificar fraude, manipulação ou criação irregular de múltiplas contas.', 'Compras promocionais continuam sujeitas às regras aplicáveis de cancelamento, troca, devolução, garantia e direito de arrependimento previstas na legislação brasileira.', 'Campanhas especiais poderão ter regulamento próprio. Em caso de conflito, as condições específicas da campanha prevalecerão para aquela promoção, sempre observada a legislação aplicável.', 'Em caso de dúvidas sobre promoções, cupons ou benefícios, entre em contato com a TEKNIX pelos canais oficiais de atendimento.'] },
  acessibilidade: { title: 'Acessibilidade na TEKNIX', paragraphs: ['Última atualização: 08 de setembro de 2026.', 'Na TEKNIX, acreditamos que a tecnologia deve aproximar pessoas, facilitar escolhas e proporcionar autonomia. Buscamos oferecer uma experiência acessível para pessoas com deficiência visual, auditiva, motora, cognitiva ou outras necessidades específicas.', 'Trabalhamos para manter uma navegação organizada e previsível, com páginas, menus, produtos, categorias, formulários e botões apresentados de forma clara.', 'Buscamos permitir o acesso às principais áreas por teclado, com ordem lógica de navegação e indicação visual de foco sempre que tecnicamente aplicável.', 'Utilizamos estruturas semânticas para auxiliar tecnologias assistivas, incluindo leitores de tela. Imagens relevantes podem receber descrições alternativas e elementos decorativos podem ser tratados para evitar informações desnecessárias.', 'Também trabalhamos com contraste, legibilidade, tamanhos de fonte, espaçamento, informações além das cores e adaptação para computadores, tablets e smartphones.', 'Campos de cadastro, login, endereço, contato e checkout são desenvolvidos buscando possuir identificação e instruções claras. Quando houver erro, buscamos apresentar informações para correção.', 'Algumas funcionalidades de terceiros, como pagamentos, mapas, vídeos e atendimento, podem ter características de acessibilidade que não são controladas diretamente pela TEKNIX.', 'A acessibilidade digital é um processo contínuo. Seguimos aprimorando navegação por teclado, compatibilidade com tecnologias assistivas, contraste, descrições, formulários e experiência móvel.', 'Se encontrar alguma barreira, informe a página, dispositivo, navegador, tecnologia assistiva utilizada e uma descrição do problema. Essas informações nos ajudam a melhorar a experiência.', 'A TEKNIX continuará trabalhando para tornar sua experiência digital mais simples, acessível e inclusiva.'] },
  'seguranca-privacidade': { title: 'Segurança e Privacidade', paragraphs: ['Cuidamos dos seus dados e usamos medidas de segurança para proteger sua conta, suas compras e suas informações pessoais.', 'Coletamos somente as informações necessárias para criar sua conta, processar pagamentos, entregar pedidos, prestar atendimento e melhorar sua experiência na TEKNIX.', 'Usamos seus dados para confirmar sua identidade, acompanhar pedidos, emitir documentos fiscais, prevenir fraudes e manter a segurança da loja.', 'O acesso às informações é limitado às pessoas e parceiros que precisam delas para realizar esses serviços. Quando compartilhamos dados com prestadores, exigimos que eles também sigam medidas de proteção e confidencialidade.', 'Os dados de pagamento são tratados por parceiros especializados e não armazenamos o número completo do seu cartão em nossos sistemas de atendimento.', 'Mantemos as informações somente pelo período necessário para cumprir as finalidades da compra, obrigações legais, prevenção de fraudes e defesa de direitos.', 'Nunca compartilhe sua senha, códigos de verificação ou dados completos de cartão por mensagens. A TEKNIX não solicita essas informações fora dos canais oficiais.', 'Podemos utilizar cookies e tecnologias semelhantes para manter a sessão, lembrar preferências, entender o uso da loja e oferecer uma navegação mais segura. Você pode controlar cookies nas configurações do seu navegador.', 'Você pode solicitar informações sobre seus dados, pedir correção de informações incompletas ou entrar em contato para esclarecer dúvidas sobre o tratamento de dados.', 'Quando aplicável, você também pode solicitar a revisão de decisões automatizadas, a eliminação de dados tratados com consentimento ou a portabilidade das informações, observadas as exceções legais.', 'Mantenha seus dados de acesso atualizados, use uma senha exclusiva e encerre a sessão quando utilizar um dispositivo compartilhado. Se notar qualquer atividade suspeita, altere sua senha e fale conosco imediatamente.', 'Esta página pode ser atualizada para refletir mudanças nos serviços, na legislação ou nas práticas de segurança. Recomendamos consultar esta área periodicamente.', 'Para dúvidas sobre privacidade, segurança da conta ou tratamento de dados, entre em contato com nosso atendimento pelos canais oficiais da TEKNIX.'] },
}

export default function LegalPage() {
  const { slug = 'regulamento' } = useParams()
  const content = CONTENT[slug] || CONTENT.regulamento
  return <main className="legal-page"><div className="legal-page-inner"><nav><Link to="/">Início</Link><span>›</span><span>{content.title}</span></nav><h1>{content.title}</h1><article>{content.paragraphs.map(text => <p key={text}>{text}</p>)}<Link className="legal-back" to="/ajuda">Ir para a Central de Ajuda →</Link></article></div></main>
}
