const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');const path=require('node:path');
function compile(file,imports){const exports={};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('require','exports',code)(name=>imports[name],exports);return exports}
const core=compile(path.resolve(__dirname,'../../../packages/core/src/pageWidgets.ts'),{});
function service(responses){const calls=[];const client={from(table){let record={table,ops:[]};calls.push(record);const query=new Proxy({}, {get(_,method){if(method==='then')return (resolve,reject)=>Promise.resolve(responses.shift()||{data:[],error:null}).then(resolve,reject);return(...args)=>{record.ops.push([method,...args]);return query}}});return query}};return{calls,...compile(path.resolve(__dirname,'../src/services/widgetEditor.ts'),{'../lib/supabase':{supabase:client},'../../../../packages/core/src/pageWidgets':core})}}
const ok=data=>({data,error:null});
const target=()=>({scope:'product:A',title:'A',path:'/produtos/A',row:{id:'A',updated_at:'version-1',version:3,status:'published',page_styles:{custom_css:'preserve',published_snapshot_v2:{old:true}}},edits:{},draft:{id:'draft-A',updated_at:'draft-1',page_styles:{}}});
test('saving draft never updates public row or product data',async()=>{const api=service([ok({id:'draft-A'})]);const t=target(),before=JSON.stringify(t.row);await api.saveEditorTarget(t,{heading:{content:{text:'Draft'}}});assert.equal(JSON.stringify(t.row),before);assert.equal(api.calls.length,1);assert.equal(api.calls[0].table,'pages');assert.ok(api.calls[0].ops.some(o=>o[0]==='eq'&&o[1]==='id'&&o[2]==='draft-A'));const update=api.calls[0].ops.find(o=>o[0]==='update')[1];assert.equal(update.page_styles.editor_draft_v2.edits.heading.content.text,'Draft');assert.equal(update.status,undefined)});
test('first draft is unpublished and scoped to one real product',async()=>{const api=service([ok({id:'new-draft'})]);const t=target();delete t.draft;await api.saveEditorTarget(t,{});const payload=api.calls[0].ops.find(o=>o[0]==='insert')[1];assert.equal(payload.status,'draft');assert.equal(payload.type,'editor_draft');assert.equal(payload.slug,'__draft__/product%3AA')});
test('publication writes history before switching the public snapshot',async()=>{const api=service([ok({id:'draft-A'}),ok({id:'history'}),ok({id:'A',status:'published'})]);await api.saveEditorTarget(target(),{heading:{content:{text:'Published A'}}},true);assert.deepEqual(api.calls.map(c=>c.table),['pages','page_publications','pages']);const history=api.calls[1].ops.find(o=>o[0]==='insert')[1];const update=api.calls[2].ops.find(o=>o[0]==='update')[1];assert.equal(history.version,4);assert.deepEqual(history.snapshot,update.page_styles.published_snapshot_v2);assert.equal(update.page_styles.custom_css,'preserve');assert.ok(api.calls[2].ops.some(o=>o[0]==='eq'&&o[1]==='id'&&o[2]==='A'));assert.equal(update.page_styles.published_snapshot_v2.page.page_styles.widget_editor_v1.heading.content.text,'Published A')});
test('a rejected snapshot cannot mark the page published',async()=>{const api=service([ok({id:'draft-A'}),{data:null,error:new Error('Snapshot denied')}]);await assert.rejects(api.saveEditorTarget(target(),{},true),/Snapshot denied/);assert.equal(api.calls.length,2);assert.equal(api.calls[1].table,'page_publications')});
test('concurrent draft writes produce an explicit conflict',async()=>{const api=service([ok(null)]);await assert.rejects(api.saveEditorTarget(target(),{}),/outra sessão/)});
test('concurrent publication cannot overwrite another public version',async()=>{const api=service([ok({id:'draft-A'}),ok({id:'history'}),ok(null)]);await assert.rejects(api.saveEditorTarget(target(),{},true),/outra sessão/);assert.ok(api.calls[2].ops.some(o=>o[0]==='eq'&&o[1]==='updated_at'&&o[2]==='version-1'))});
test('existing snapshots are immutable during legacy initialization',async()=>{const api=service([]);const t=target();assert.equal(await api.ensurePublishedSnapshot(t.row),t.row);assert.equal(api.calls.length,0)});
test('snapshot embeds changed tree without leaking editor history key into widget edits',async()=>{const api=service([ok({id:'draft-A'}),ok({id:'history'}),ok({id:'A'})]);await api.saveEditorTarget(target(),{__tree__:{tree:{page:{id:'A'},sections:[{id:'s'}],containers:[],widgets:[]}}},true);const snapshot=api.calls[1].ops.find(o=>o[0]==='insert')[1].snapshot;assert.equal(snapshot.sections[0].id,'s');assert.equal(snapshot.page.page_styles.widget_editor_v1.__tree__,undefined)});
test('public paths normalize root and nested URLs',()=>{const api=service([]);assert.equal(api.pagePath('/'),'/');assert.equal(api.pagePath(''),'/');assert.equal(api.pagePath('//campanha/oferta/'),'/campanha/oferta')});
test('legacy override CSS cannot inject other page selectors',()=>{assert.deepEqual(core.safeStyle({color:'red',width:'1px;}body{display:none',backgroundColor:'url(https://example.com)'}),{color:'red'});assert.equal(core.safeMediaUrl('javascript:alert(1)'),undefined)});
